//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.SignupReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SignupReference.ISignup")]
    public interface ISignup {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignup/Signup", ReplyAction="http://tempuri.org/ISignup/SignupResponse")]
        bool Signup(ContactManagement.User.user u);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISignup/Signup", ReplyAction="http://tempuri.org/ISignup/SignupResponse")]
        System.Threading.Tasks.Task<bool> SignupAsync(ContactManagement.User.user u);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISignupChannel : WebClient.SignupReference.ISignup, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignupClient : System.ServiceModel.ClientBase<WebClient.SignupReference.ISignup>, WebClient.SignupReference.ISignup {
        
        public SignupClient() {
        }
        
        public SignupClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SignupClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignupClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SignupClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Signup(ContactManagement.User.user u) {
            return base.Channel.Signup(u);
        }
        
        public System.Threading.Tasks.Task<bool> SignupAsync(ContactManagement.User.user u) {
            return base.Channel.SignupAsync(u);
        }
    }
}
